.TH ID-SHR-EXTRACT "1" "April 2011" "id-shr-extract" "User Commands"
.SH NAME
id-shr-extract \- ID SHR data file extractor
.SH SYNOPSIS
id-shr-extract <filename.SHR>
.SH DESCRIPTION
id-shr-extract is a tool to extract the data from .SHR installer files.
.
These files were used by early ID Software games.
